---
generic-app:
  nameOverride: sample-api

  pods:
    image:
      name: fcruzcoelho/sample-api
      pullPolicy: Always

    env:
      - name: APP_VERSION
        value: "{{ .Values.image.tag }}"