base-app:
  nameOverride: "sample-api"
  pods:
    replicas: 2
    image:
      name: "placeholder"
      tag: "placeholder"
      pullPolicy: IfNotPresent

  service:
    enabled: true
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http

  rollout:
    enabled: true
    strategy:
      canary:
        steps:
        - setWeight: 20
        - pause: {}