base-app:
  nameOverride: "sample-api"
  pods:
    image:
      name: "placeholder"
      tag: "placeholder"
      pullPolicy: IfNotPresent
  
    affinity:
      rules: {}

  service:
    enabled: true
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
