apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-api-prod
  namespace: argocd
  labels:
    app.kubernetes.io/name: sample-api
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: applications
spec:
  project: apps
  source:
    repoURL: https://github.com/estudosdevops/sample-api.git
    targetRevision: main
    path: charts/sample-api
    helm:
      releaseName: sample-api
      valueFiles:
        - values-prod.yaml
      ignoreMissingValueFiles: true
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
